sudo: false
language: node_js
before_install:
  - npm update -g npm
before_script:
  - npm install -g grunt-cli
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
matrix:
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.11"
  fast_finish: true
script: "npm run-script test-travis"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
notifications:
  email: false
